# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170610_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='jornalista',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AlterField(
            model_name='rh',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
