# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170610_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCaderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('conteudo', models.TextField()),
                ('caderno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Caderno')),
            ],
        ),
        migrations.AddField(
            model_name='caderno',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ListaCaderno'),
        ),
    ]
