# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170611_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caderno',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ListaCaderno'),
        ),
    ]
