# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170611_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='caderno',
            name='descricao',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
