# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_caderno_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caderno',
            name='descricao',
            field=models.TextField(max_length=30),
        ),
    ]
